/**
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
    let c = 0;
    for(let i = 0; i < t.length; i++) {
        // bit operator can only act on integers
        // String.charCodeAt(i) returns char's Unicode, it's a 16 bits integer
        // BTW: String.charAt(i) returns a char. In fact, the char is a string with length 1
        c = c ^ s.charCodeAt(i) ^ t.charCodeAt(i);
    }
    // String.fromCharCode() can create a string by Unicode
    return String.fromCharCode(c);
};
